name: campusconnect
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.de

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.3
  firebase_auth: ^1.1.4
  firebase_core: ^1.24.0
  fluttertoast: ^8.1.2
  animated_notch_bottom_bar: ^0.0.6
  flutter_radar_chart: ^0.2.1
  objectbox_flutter_libs: any
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  provider: ^6.0.5
  flutter_screenutil: ^5.7.0
  pinput: ^2.2.31
  flutter_svg: ^2.0.4
  dot_navigation_bar: ^1.0.1+4
  pie_chart: ^5.3.2
  objectbox: ^2.0.0
  path_provider: ^2.0.14
  path: ^1.8.2
  get_storage: ^2.1.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  image_picker: ^0.8.5+3
  card_swiper: ^2.0.4
  shared_preferences: ^2.1.0
  flutter_image_compress: ^1.1.3
  encrypt: ^5.0.1
  restart_app: ^1.1.2
  flutter_windowmanager: ^0.2.0
  flutter_native_splash: ^2.2.19
  animated_text_kit: ^4.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_launcher_icons: "^0.13.0"
  flutter_lints: ^2.0.0

  objectbox_generator: any
dependency_overrides:
  firebase_core_platform_interface: 4.5.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
